### ISSUE TITLE
Can't send message to custom url

### ISSUE THREAD

**Issue by nestorghh** [carpedm20/fbchat#437] opened 2019-07-01 23:44 UTC
## Description of the problem
Example: Getting error whenever I try to send a message to a user who has a customize url. Can we send messages without using the numeric userid but using the customize url.
## Code to reproduce
```py
# Example code
from fbchat import Client
from fbchat.models import *

email='something_random@yyy.com'
passw='whatever'
client = Client(email, passw)
message_='this is my message'
userid='userid_url'

client.send(Message(text=message_), thread_id=userid, thread_type=ThreadType.USER)


## Traceback
```
Traceback (most recent call last):

  File "<ipython-input-9-3635c575dce3>", line 4, in <module>
    client.send(Message(text=message_), thread_id=userid, thread_type=ThreadType.USER)

  File "/home/nestorghh/anaconda3/lib/python3.7/site-packages/fbchat/_client.py", line 1362, in send
    return self._doSendRequest(data)

  File "/home/nestorghh/anaconda3/lib/python3.7/site-packages/fbchat/_client.py", line 1321, in _doSendRequest
    j = self._post(self._req_url.SEND, data, fix_request=True, as_json=True)

  File "/home/nestorghh/anaconda3/lib/python3.7/site-packages/fbchat/_client.py", line 202, in _post
    raise e

  File "/home/nestorghh/anaconda3/lib/python3.7/site-packages/fbchat/_client.py", line 190, in _post
    return check_request(r, as_json=as_json)

  File "/home/nestorghh/anaconda3/lib/python3.7/site-packages/fbchat/_util.py", line 231, in check_request
    request_status_code=r.status_code,

FBchatFacebookError: Error when sending request: Got 500 response

```

## Environment information
- Python version 3.7
- `fbchat` version most recent grom github
- If relevant, output from `$ python -m pip list`

If you have done any research, include that.
Make sure to redact all personal information.

The documentation suggests that one can use the costomize userid and it should work. See https://fbchat.readthedocs.io/en/master/intro.html. Another option is to use an API like https://findmyfbid.in/developer-api/ to get the integer userid associated with the given url and then run fbchat normally. However, I'd like to avoid doing this. Is it possible to do this?

**Comment by madsmtm** [comment] 2019-07-02 18:17
No, you can't send messages using just the url/custom username, you'll have to use the numeric ID, sorry 😕.

However, you can probably retrieve the ID in a number of ways, one solution would be to just search for the user, using their custom username:
```python
user = client.searchForUsers("custom_username", limit=1)[0]
user_id = user.uid
```

**Comment by madsmtm** [comment] 2020-01-09 11:20
Closing, assuming the provided workaround was sufficient. If not, feel free to reopen, and we can perhaps figure something else out 😉

**Comment by madsmtm** [comment] 2020-01-09 11:37
Also, it's a duplicate of #344 😉

**Closed by madsmtm** 2020-01-09 11:37 UTC
Labels: question
