### ISSUE TITLE
fetchUnread() is broken

### ISSUE THREAD

**Issue by harishankar18** [carpedm20/fbchat#253] opened 2018-01-29 17:08 UTC
HI,

fetchUnread() is broken , getting following error.
fbchat.models.FBchatFacebookError: Error when sending request: Got 404 response

**Comment by madsmtm** [comment] 2018-01-29 19:47
Duplicate of #124, but yes, this is still a problem, and I haven't found a solution yet

**Closed by madsmtm** 2018-01-29 19:47 UTC
