### ISSUE TITLE
File Upload feature is missing

### ISSUE THREAD

**Issue by HiteshPatel0101** [carpedm20/fbchat#245] opened 2018-01-12 11:40 UTC
I want to send file over messenger, can you please update API.
I can send file over facebook desktop browser and using Graph API.

#enhancement

**Comment by madsmtm** [comment] 2018-01-12 13:02
Duplicate of #194, will be resolved in `v2.0.0`

**Closed by madsmtm** 2018-01-12 13:02 UTC

**Comment by kapi2289** [comment] 2018-08-09 18:37
Added in #318!
