### ISSUE TITLE
onMessage stopped working.

### ISSUE THREAD

**Issue by Nikas36** [carpedm20/fbchat#483] opened 2019-11-15 18:43 UTC
## Description of the problem
I have created a messenger chatbot, and suddenly all of it's functions stopped working today since they are based on the 'onMessage' function.

Even the most basic setup containing "onMessage" doesn't work:

## Code to reproduce
```py
from fbchat import Client
from fbchat.models import *
import pickle
import time

import logging
logging.basicConfig(level=logging.DEBUG)

with open('/home/pi/Documents/FBBotV4/data/pass.txt', 'rt') as pass_txt:
    passwd = pass_txt

class Client(Client):
    def onMessage(self, message_object, **kwargs):
        print(message_object)

client = Client('[...]', passwd)
client.listen()
```

However, this works and sends messages normally:

## Working Code
```py
from fbchat import Client
from fbchat.models import *
import pickle
import time

import logging
logging.basicConfig(level=logging.DEBUG)

with open('/home/pi/Documents/FBBotV4/data/pass.txt', 'rt') as pass_txt:
    passwd = pass_txt

client = Client('[...]', passwd)

client.send(Message(text='$> test'), thread_id='[...]', thread_type=ThreadType.GROUP)
```

## Environment information
- Python version: Python 3.7.3 
- `fbchat` version: 1.8.3

**Comment by szymonszl** [comment] 2019-11-15 20:16
I have quickly checked and I can confirm, all my bots stopped reacting too. I'll try to take a closer look when I'm home, but I suspect some breaking change within FB (again)

**Comment by szymonszl** [comment] 2019-11-15 21:28
I have done a little test, I started only the listener (on a unmodified, unsubclassed Client) with DEBUG logging, and I couldn't get a single message to receive. Here are the (UIDs and DTSGs mildly redacted) logs:

```
INFO:fbchat:Logging in XXXX@XXXX...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): m.facebook.com:443
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET / HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "POST /login.php?login_attempt=1 HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /qp/interstitial/?promotion=AZLH_o[...]cEmp23Omio&continue_url=%2Flogin%2F&show_chrome=1&trigger=m_logged_in&refsrc=https%3A%2F%2Fwww.facebook.com%2F&_rdr HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /login/?_rdr HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /home.php?_rdr HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.facebook.com:443
DEBUG:urllib3.connectionpool:https://www.facebook.com:443 "GET / HTTP/1.1" 200 None
INFO:fbchat:Login of szymszlk@yandex.com successful.
DEBUG:urllib3.connectionpool:https://www.facebook.com:443 "POST /messaging/send/ HTTP/1.1" 200 None
DEBUG:fbchat:{'__ar': 1, 'payload': {'actions': [{'thread_id': '', 'thread_fbid': '', 'other_user_fbid': '1000052716XXXXX', 'action_type': 'ma-type:send-message', 'client_thread_id': None, 'message_id': 'mid.$cAAAADRjHDwh0oiW_4lucOB2vjrgH', 'client_message_id': '66012128539688XXXXX', 'status': 1, 'timestamp': 1573851789282, 'attachments': [], 'graphql_payload': None, 'for_page': False, 'is_one_way_sent': False}], 'payload_source': 'server_send_message'}, 'bootloadable': {}, 'ixData': {}, 'bxData': {}, 'gkxData': {}, 'qexData': {}, 'lid': '67596419646468XXXXX'}
# <The message "test" is received by me>
INFO:fbchat:Listening...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): 0-edge-chat.facebook.com:443
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /active_ping?seq=0&channel=p_10002687688XXXX&clientid=2925560a&partition=-2&cap=0&uid=100026876882XXX&viewer_uid=1000XXX&state=active&__a=1&__req=2&__rev=1001438306&fb_dtsg=XXX HTTP/1.1" 200 48
DEBUG:fbchat:{'t': 'pong'}
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /pull?seq=0&msgs_recv=0&clientid=2925560a&state=active&__a=1&__req=3&__rev=1001438306&fb_dtsg=XXX HTTP/1.1" 200 106
DEBUG:fbchat:{'t': 'lb', 'lb_info': {'sticky': '1272', 'pool': 'rprn0c01_chatproxy-regional'}}
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /active_ping?seq=0&channel=p_10002687688XXXX&clientid=2925560a&partition=-2&cap=0&uid=100026876882XXX&sticky_token=1272&sticky_pool=rprn0c01_chatproxy-regional&viewer_uid=10002687688XXXX&state=active&__a=1&__req=4&__rev=1001438306&fb_dtsg=XXX HTTP/1.1" 200 48
DEBUG:fbchat:{'t': 'pong'}
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /pull?seq=0&msgs_recv=0&sticky_token=1272&sticky_pool=rprn0c01_chatproxy-regional&clientid=2925560a&state=active&__a=1&__req=5&__rev=1001438306&fb_dtsg=XXX HTTP/1.1" 200 123
DEBUG:fbchat:{'t': 'fullReload', 'seq': 1, 'u': 100026876882531, 'ms': [{'type': 'qprimer', 'made': '1573851790930'}]}
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /active_ping?seq=1&channel=p_10002687688XXXX&clientid=2925560a&partition=-2&cap=0&uid=10002687688XXXX&sticky_token=1272&sticky_pool=rprn0c01_chatproxy-regional&viewer_uid=10002687688XXXX&state=active&__a=1&__req=6&__rev=1001438306&fb_dtsg=XXX HTTP/1.1" 200 48
DEBUG:fbchat:{'t': 'pong'}
# <I send a message "test" right now>
# <I send a message "hello? right now>
# <nothing new appears, after 20 seconds i close the script>
^C
```
The only serverside messages I could receive were pongs.

I've also opened up DevTools on facebook mobile chat, trying to find any trace of messages, but the only /pull with informations relating to messages was:
```json
for (;;); {"t":"msg","seq":5,"u":10002687688XXXX,"ms":[{"type":"inbox","seen_timestamp":0,"recent_unread":1,"unread":1,"unseen":0}]}
```
with the rest being `heartbeat`s.

I'll try to look around more, because it's very weird I couldn't find a single trace of a message being delivered.

**Comment by Nikas36** [comment] 2019-11-15 21:37
I am getting roughly the same outputs with debug logging on.

**Comment by szymonszl** [comment] 2019-11-15 21:39
Wait, I have just noticed a websocket connection, and it seems to bring bad news...

![Screenshot_2019-11-15_22-31-15](https://user-images.githubusercontent.com/26420110/68977228-0ecfba80-07f8-11ea-9465-0549287bc5a7.png)

While the content is mostly JSON, it seems to have some kind of binary wrapping which I suspect will cause problems. The only thing I have noticed so far is that `c000` is ping (client->server) and `d000` is pong (server->client), with them being exchanged around every 10 seconds.

**Comment by Nikas36** [comment] 2019-11-16 10:14
Any updates on the issue?

**Comment by tulir** [comment] 2019-11-20 20:15
The new protocol is MQTT 3.1.0 over websockets. I have a basic implementation for receiving events  that way in my asyncio fork of fbchat: https://github.com/tulir/fbchat-asyncio/blob/yet-another-rewrite/fbchat/_client.py#L2749-L2882

**Comment by ccfiel** [comment] 2019-11-23 02:05
this is already solve using this https://github.com/tulir/fbchat-asyncio

**Comment by kapi2289** [comment] 2019-11-23 11:29
Don't close the issue, because it's still problem in the `fbchat` origin.

**Comment by chelazarcia** [comment] 2019-11-25 23:51
Same here. The bot stopped working and has not been able to receive any more messages.

**Comment by YannickGibson** [comment] 2019-11-26 13:25
Im having same problem

**Comment by madsmtm** [comment] 2019-11-27 12:22
Sorry about the delay. As @tulir said, the protocol is MQTT 3.1.0 over websockets, and that means we'll have to make some (possibly major?) modifications to our current setup.

This'll take me time to fix, and my exams are coming up, so I won't have that time the next few weeks. If anyone is keep on fixing this, please do, but otherwise, for now, the solution I'd recommend is using @tulir's fork.

**Comment by madsmtm** [comment] 2019-11-27 12:22
Oops, accidentally hit close...

**Comment by syspic** [comment] 2019-12-20 06:32
Is it just me or are all the on... methods not working? I dont seem to be getting any logging info on any of the methods
Also, I'm new to this. I've made a very simple thing in the past, but how can I go about using the forked version?  I see that i have to install it, but will that interfere with my fbchat install?
sorry for all the noob questions haha

**Comment by PythonNut** [comment] 2019-12-20 06:59
How difficult would it be to port the changes from `fbchat-asyncio` back to this implementation?

**Comment by Nikas36** [comment] 2019-12-20 09:17
> Also, I'm new to this. I've made a very simple thing in the past, but how can I go about using the forked version? I see that i have to install it, but will that interfere with my fbchat install?

I had to uninstall `fbchat` and install `fbchat-asyncio` using

```
git clone https://github.com/tulir/fbchat-asyncio.git
cd fbchat-asyncio
pip install .
```

Try checking out the examples over at https://github.com/tulir/fbchat-asyncio/tree/master/examples

The three main differences you should worry about are:
- The starting / log-in function
- `async def [...]`s and `await`s before function and class definitions and calls
- snake_case instead of camelCase

Sorry if I didn't explain it well, I'm new to this as well :/

**Comment by syspic** [comment] 2019-12-20 17:27
@PythonNut  wondering the same thing.  I'd like to use this fbchat when this issue is fixed

@Nikas36  darn.  I'll have to try it when I get a chance later tonight. Did pip install not work? I'm a bit confused because the examples import from fbchat too

Anyway I'll try it later and update. But also this thread doesn't feel like the right place to talk about that. Is there a better place to do it? Maybe start a new quesion thread about it? Idk.  I normally use GitHub as a reference so I don't know how this stuff works

**Comment by RONNCC** [comment] 2019-12-27 04:09
+1 still interested in the fix when y'all have time :)

**Comment by Felixim0** [comment] 2019-12-30 17:32
+1 still interested - Hello! I was using this for exams xD

**Comment by YannickGibson** [comment] 2019-12-31 10:38
> @PythonNut wondering the same thing. I'd like to use this fbchat when this issue is fixed
> 
> @Nikas36 darn. I'll have to try it when I get a chance later. Did pip install not work? I'm a bit confused because the examples import from fbchat too
> 
> Anyway I'll try it later and update. But also this thread doesn't feel like the right place to talk about that. Is there a better place to do it? Maybe start a new quesion thread about it? Idk. I normally use GitHub as a reference so I don't know how this stuff works
> 
> edit: yeah I dont think I got it working :(

in your cmd: pip install fbchat-asyncio
then in your project you import like this: import asyncio

**Comment by madsmtm** [comment] 2020-01-05 19:48
I've worked on this over the holidays, and my work is finally near finished, sorry for the long delay.

In a few days, I'll release a new version!

**Comment by madsmtm** [comment] 2020-01-06 10:06
I've released `v1.9.0`, which fixes this! 🎉🚀

You can install this using `pip install -U fbchat`.

It should be fairly stable, but I'll need your help testing the last few odd corners, so feel absolutely free to open an issue if you find anything!

Thanks for your patience 🙏👍

**Closed by madsmtm** 2020-01-06 10:06 UTC
Labels: bug, help wanted

**Comment by giongto35** [comment] 2020-01-06 17:11
I still got "MQTT Error: A network protocol error occurred when communicating with the broker." using v1.9.0. Anyone has the same issue.

**Comment by h4o** [comment] 2020-01-06 23:02
> I still got "MQTT Error: A network protocol error occurred when communicating with the broker." using v1.9.0. Anyone has the same issue.

Yes got the same error here. Do I have to upgrade another dependency (or python itself? it's running 3.4 now) ?

**Comment by madsmtm** [comment] 2020-01-07 16:46
@giongto35 and @h4o, thanks for the report, the issue is being tracked in #495, so please submit further info there 👍
