### ISSUE TITLE
client.fetchAllUsers() throwing FBChatException

### ISSUE THREAD

**Issue by choitomas66** [carpedm20/fbchat#330] opened 2018-09-06 19:45 UTC
I was wondering if this method was obsolete? I got the following traceback:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/falcon/.local/lib/python2.7/site-packages/fbchat/client.py", line 811, in fetchThreadList
    return [graphql_to_thread(node) for node in j['viewer']['message_threads']['nodes']]
  File "/home/falcon/.local/lib/python2.7/site-packages/fbchat/graphql.py", line 177, in graphql_to_thread
    return graphql_to_group(thread)
  File "/home/falcon/.local/lib/python2.7/site-packages/fbchat/graphql.py", line 211, in graphql_to_group
    c_info = get_customization_info(group)
  File "/home/falcon/.local/lib/python2.7/site-packages/fbchat/graphql.py", line 43, in get_customization_info
    'color': graphql_color_to_enum(info.get('outgoing_bubble_color'))
  File "/home/falcon/.local/lib/python2.7/site-packages/fbchat/graphql.py", line 34, in graphql_color_to_enum
    raise FBchatException('Could not get ThreadColor from color: {}'.format(color))

**fbchat.models.FBchatException: Could not get ThreadColor from color: FF8BB88C**

**Comment by choitomas66** [comment] 2018-09-06 19:54
Woops. Should've done a bit more research before posting the issue. Adding the color to models.py should fix it.

**Comment by choitomas66** [comment] 2018-09-06 20:09
I just did a local fix by adding the color to the ThreadColor class in models.py 

Not sure what the root cause is however.

**Comment by madsmtm** [comment] 2018-09-07 08:54
Duplicate of #220, if anyone feels like implementing a backwards compatible fix, feel free

**Closed** 2020-01-09 11:46 UTC
Labels: duplicate
