### ISSUE TITLE
Sending a url as an attachment?

### ISSUE THREAD

**Issue by rocketLeagueTraderJoe** [carpedm20/fbchat#524] opened 2020-01-30 14:35 UTC
I'm trying to send a url as an attachment but I'm having some difficulty figuring out how it's done.  I've tried filling out the url and original_url fields for ShareAttachment, but the little url box doesn't show up when I send the message that it's attached to. Does anyone have an example for how it's properly done?

**Comment by madsmtm** [comment] 2020-01-30 22:15
Duplicate of #283, so I'll close this.

The short answer, this is not yet implemented, if anyone want to do it, please be my guest!

**Closed by madsmtm** 2020-01-30 22:15 UTC
