### ISSUE TITLE
GRAPHQL ERROR WHEN PUTTING A LIMIT BIGGER THAN 10k FOR fetchThreadMessages()

### ISSUE THREAD

**Issue by MrGeorgeMuresan** [carpedm20/fbchat#576] opened 2020-05-17 09:22 UTC
## Description of the problem
GRAPHQL ERROR WHEN PUTTING A LIMIT BIGGER THAN 2k FOR fetchThreadMessages()
## Code to reproduce
# Example code
from fbchat import Client

client = Client("email", "password")

group = client.fetchGroupInfo('group_id')['group_id']
print(group.message_count)
messages = client.fetchThreadMessages(thread_id = 'thread_id', limit=2000)
messages.reverse()
with open(r"mesaje_grup_clasa.txt", "w", encoding='utf-8') as file:
    for message in messages:
        author = client.fetchUserInfo(message.author)[message.author]
        print("Autor: {0}, Mesaj: {1}".format(author.name, message.text))
        file.write("Autor: {0}, Mesaj: {1}".format(author.name, message.text))
        file.write("\n")
    file.close()
```

## Traceback
```

  Message=GraphQL error #None: Errors while executing operation "MessengerThreads": At Query.message_thread:MessageThread.messages:MessagesOfThreadConnection.page_info: Field implementation threw an exception. Check your server logs for more information. / None
  Source=C:\Users\name\Desktop\RANDOM TEXT BOT\main.py
  StackTrace:
  File "C:\Users\name\Desktop\RANDOM TEXT BOT\main.py", line 8, in <module>
    messages = client.fetchThreadMessages(thread_id = '1846138885477788', limit=2000)

```

## Environment information
- Python version Python 3.8 (32 bit version)
- `fbchat` version - fbchat==1.9.6

WORK AROUND 

I ADDED A TRY AND EXCEPT and incresead the limit and it worked
try:
    messages = client.fetchThreadMessages(thread_id = 'thread_id', limit=5000)
    messages.reverse()

    with open(r"mesaje_grup_clasa.txt", "w", encoding='utf-8') as file:
        for message in messages:
            author = client.fetchUserInfo(message.author)[message.author]
            print("Autor: {0}, Mesaj: {1}".format(author.name, message.text))
            file.write("Autor: {0}, Mesaj: {1}".format(author.name, message.text))
            file.write("\n")
        file.close()
except Exception as e:
    print("Da meri in pula")
    messages = client.fetchThreadMessages(thread_id = '', limit=5000)
    messages.reverse()

    with open(r"mesaje_grup_clasa.txt", "w", encoding='utf-8') as file:
        for message in messages:
            author = client.fetchUserInfo(message.author)[message.author]
            print("Autor: {0}, Mesaj: {1}".format(author.name, message.text))
            file.write("Autor: {0}, Mesaj: {1}".format(author.name, message.text))
            file.write("\n")
        file.close()

**Comment by madsmtm** [comment] 2020-06-07 12:45
This is a duplicate of https://github.com/carpedm20/fbchat/issues/503. As said there, this is handled in `v2` (on the `master` branch), but I won't backport the fix to `v1`

**Closed by madsmtm** 2020-06-07 12:45 UTC
