### ISSUE TITLE
 print("users' IDs: {}".format(user.uid for user in users)) fails.

### ISSUE THREAD

**Issue by olemr** [carpedm20/fbchat#332] opened 2018-09-08 23:44 UTC
Following the example in order to retrieve a uid other than your own, this command fails:

```
>>> print("users' IDs: {}".format(user.uid for user in users))
users' IDs: <generator object <genexpr> at 0x7f976aa8afa0>
```

I suspect this is because user names in my chat list contains national characters.
Trying just:
```
>>> print (users)
[<USERs listed up til ... >, 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf8' in position 13: ordinal not in range(128)

```
Running:
```
>>>import sys
>>>reload(sys)
>>>sys.setdefaultencoding('utf8')
>>> print (users)
```
luckily listed the user I wanted, and then hung my terminal window.

This command still don't work:
```
>>> print("users' IDs: {}".format(user.uid for user in users))
users' IDs: <generator object <genexpr> at 0x7f976aa8afa0>
```

**Comment by madsmtm** [comment] 2018-09-09 12:27
This is really two issues:
The example is written wrongly, it prints `<generator...>` because we use a generator expression, not a list comprehension. The correct code is fixed in 08117e7a54a33f25812f9bd970e3c2e9cb96a17c:
```py
print("users' IDs: {}".format([user.uid for user in users]))
```

The encoding errors are a duplicate of #302

**Closed** 2018-09-09 12:27 UTC
Labels: bug, duplicate
