### ISSUE TITLE
AudioAttachment

### ISSUE THREAD

**Issue by rkuo2000** [carpedm20/fbchat#308] opened 2018-07-01 07:23 UTC
How to send an audio attachment ?

client.send(Message(text='send an audio', attachments=AudioAttachment('bonjour.mp3'), thread_id=thread_id, thread_type=thread_type)

**Comment by madsmtm** [comment] 2018-07-01 08:54
Related to, if not a duplicate of, #194. To answer your question, then this is not yet implemeted ;)

**Comment by kapi2289** [comment] 2018-08-09 18:37
Added in #318!

**Comment by madsmtm** [comment] 2018-08-29 22:33
Fixed in release `v1.4.0`. The relevant method is called `sendLocalFiles`

**Closed by madsmtm** 2018-08-29 22:33 UTC
Labels: question
