### ISSUE TITLE
sendRemoteImage - Error

### ISSUE THREAD

**Issue by chatango-kotarou** [carpedm20/fbchat#231] opened 2017-11-25 18:09 UTC
it seems _uploadImage errors with a KeyError when attempting to grab the image id.

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\fbchat\client.py", line 1518, in _parseMessage
    thread_id=thread_id, thread_type=thread_type, ts=ts, metadata=metadata, msg=m)
  File "C:/Users/User/PycharmProjects/Python/bots/fb/bot.py", line 51, in onMessage
    self.sendImageURL(image, id=thread_id, type=thread_type, msg="Google Image")
  File "C:\Users\User\PycharmProjects\Python\bots\fb\fblib.py", line 39, in sendImageURL
    self._mgr._inst.sendRemoteImage(url, thread_id=id, thread_type=type, message=Message(msg))
  File "C:\Python27\lib\site-packages\fbchat\client.py", line 1018, in sendRemoteImage
    image_id = self._uploadImage(image_url, remote_image, mimetype)
  File "C:\Python27\lib\site-packages\fbchat\client.py", line 981, in _uploadImage
    return j['payload']['metadata'][0]['image_id']
KeyError: u'image_id'

**Comment by chatango-kotarou** [comment] 2017-11-26 00:14
further expect ion shows that the metadata returns as a empty dict

**Comment by chatango-kotarou** [comment] 2017-11-26 00:14
{u'lid': u'6492507727951238960', u'__ar': 1, u'gkxData': {}, u'bootloadable': {}, u'ixData': {}, u'payload': {u'uploadID': None, u'metadata': []}}
Exception in parsing of {u'queue': 100006431735154L, u'ofd_ts': 1511654745177L, u'iseq': 4807, u'type': u'delta', u'delta': {u'body': u'Gi test', u'irisSeqId': u'4807', u'attachments': [], u'messageMetadata': {u'tags': [u'source:chat:orca'], u'actorFbId': u'100006431735154', u'messageId': u'mid.$gAAUUfZeZgJpmJuor8lf9aTe1yfiB', u'offlineThreadingId': u'6340339538401556609', u'timestamp': u'1511654745074', u'threadKey': {u'threadFbId': u'1429904530440346'}}, u'ttl': u'TTL_OFF', u'class': u'NewMessage'}}
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\fbchat\client.py", line 1519, in _parseMessage
    thread_id=thread_id, thread_type=thread_type, ts=ts, metadata=metadata, msg=m)
  File "C:/Users/User/PycharmProjects/Python/bots/fb/bot.py", line 65, in onMessage
    self.sendImage(image, id=thread_id, type=thread_type, msg="Google Image")
  File "C:\Users\User\PycharmProjects\Python\bots\fb\fblib.py", line 39, in sendImage
    self._mgr._inst.sendLocalImage(img, thread_id=id, thread_type=type, message=Message(msg))
  File "C:\Python27\lib\site-packages\fbchat\client.py", line 1037, in sendLocalImage
    image_id = self._uploadImage(image_path, open(image_path, 'rb'), mimetype)
  File "C:\Python27\lib\site-packages\fbchat\client.py", line 982, in _uploadImage
    return j['payload']['metadata'][0]['image_id']
IndexError: list index out of range

**Comment by madsmtm** [comment] 2017-12-10 19:02
Thanks for posting this issue, though I can't reproduce it. Maybe it's got something to do with the image you're trying to upload? What does your code look like?

**Comment by madsmtm** [comment] 2018-08-29 22:51
Might be fixed by #318, in release `v1.4.0`

**Comment by madsmtm** [comment] 2020-01-09 11:51
I'll assume the above update fixes this

**Closed by madsmtm** 2020-01-09 11:51 UTC
Labels: bug
