### ISSUE TITLE
Link preview in sent messages

### ISSUE THREAD

**Issue by andrejeronimo** [carpedm20/fbchat#451] opened 2019-07-22 09:50 UTC
## Description
Would be nice if we could send messages with link previews.

## Example
![image](https://user-images.githubusercontent.com/7091189/61623362-686f1080-ac6e-11e9-9aed-469f963c4bd7.png)

**Comment by kapi2289** [comment] 2019-07-22 12:21
Duplicate of #424

**Comment by madsmtm** [comment] 2019-07-22 20:57
Agree with @kapi2289, closing as duplicate

**Closed by madsmtm** 2019-07-22 20:57 UTC
Labels: duplicate
