### ISSUE TITLE
sendLocalImage is broken?

### ISSUE THREAD

**Issue by PythonNut** [carpedm20/fbchat#240] opened 2018-01-05 07:12 UTC
This is on the latest version on pypi:

```
Traceback (most recent call last):
[...]
  File "[...]/fbchat/client.py", line 1037, in sendLocalImage
    return self.sendImage(image_id=image_id, message=message, thread_id=thread_id, thread_type=thread_type, is_gif=is_gif)
  File "[...]/fbchat/client.py", line 990, in sendImage
    data = self._getSendData(message=message, thread_id=thread_id, thread_type=thread_type)
  File "[...]/fbchat/client.py", line 898, in _getSendData
    if message.text or message.sticker or message.emoji_size:
AttributeError: 'str' object has no attribute 'text'
```

**Comment by madsmtm** [comment] 2018-01-05 08:51
I know what the issue is, it happened after I changed the message parameter to be able to be defined as a `Message` object, instead of a string, but I must have forgotten to include a translation from strings to the Message object in `sendLocalImage`. I'll fix it in a few hours, in `v1.2.1`

**Comment by madsmtm** [comment] 2018-01-08 20:56
Sorry, I forgot about this until now, but it should be fixed in the latest version

**Closed** 2018-01-08 20:55 UTC
Labels: bug

**Comment by PythonNut** [comment] 2018-01-08 21:27
Thanks a bunch, it's working again.

**Comment by dmoonat** [comment] 2018-01-31 15:46
Traceback (most recent call last):
  File "C:/Users/user/AppData/Local/Programs/Python/Python35/Programs/fb1.py", line 12, in <module>
    sent = client.send(msg,friend.uid)
NameError: name 'message' is not defined

having the similar error as above..plz help

**Comment by madsmtm** [comment] 2018-01-31 15:56
@dmoonat, these issues are unrelated, though if you provide me with the full stack trace and your entire program, I can perhaps still help you out?

**Comment by dmoonat** [comment] 2018-01-31 16:24
import fbchat
from getpass import getpass
username = str(input("Username: "))
client = fbchat.Client(username, getpass())
#no_of_friends = int(input("Number of friends: "))
#for i in range(no_of_friends):
name = str(input("Name: "))
friends = client.searchForUsers(name)  # return a list of names
friend = friends[0]
#friend =name
msg = str(input("Message: "))
sent = client.send(msg,friend.uid)
if sent:
      print("Message sent successfully!")

error:
Traceback (most recent call last):
  File "C:/Users/user/AppData/Local/Programs/Python/Python35/Programs/fb1.py", line 12, in <module>
    sent = client.send(message(msg),friend.uid)
NameError: name 'message' is not defined

**Comment by madsmtm** [comment] 2018-01-31 19:04
You're supposed to give the `send` function a `Message` object as the first parameter, something like this: `client.send(Message(text=msg), thread_id=friend.uid)`. Alternatively you could use `client.sendMessage(msg, thread_id=friend.uid)` (Which is actually deprecated, since the first one is much more powerfull)

**Comment by dmoonat** [comment] 2018-02-01 12:31
I have tried it but it still gives error :
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\Programs\fb1.py", line 12, in <module>
    sent = client.send(Message(text=msg),friend.uid)
NameError: name 'Message' is not defined
>>>

**Comment by dmoonat** [comment] 2018-02-01 12:42
Thanks for the help.

**Comment by satishegov** [comment] 2018-04-10 07:44
hey #dmoonat        still i am not able to rectify the bug ,could you send the complete code .
