### ISSUE TITLE
AttributeError: 'module' object has no attribute 'signature'

### ISSUE THREAD

**Issue by Kudu** [carpedm20/fbchat#136] opened 2017-05-09 05:14 UTC
I get the following error when attempting to simply initialize the client:
```
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    client = fbchat.Client(fb_username, fb_password)
  File "/usr/local/lib/python2.7/dist-packages/fbchat/client.py", line 113, in __init__
    self.onLoggingIn += lambda email: log.info("Logging in %s..." % email)
  File "/usr/local/lib/python2.7/dist-packages/fbchat/event_hook.py", line 26, in __iadd__
    params = inspect.signature(handler).parameters
AttributeError: 'module' object has no attribute 'signature'
```

**Comment by madsmtm** [comment] 2017-05-09 05:38
I accidentally merged a PR before it was ready, so this is the cause. Try updating `fbchat` again :)

**Comment by Dainius14** [comment] 2017-05-09 07:08
Are you on Python 2?

**Closed** 2017-05-09 14:39 UTC

**Comment by neenams** [comment] 2017-10-10 09:00
Could you please share what is this error ? and how to revolve it ? I am getting similar error on open BMC compilation

**Comment by madsmtm** [comment] 2017-10-10 13:27
@neenams the code responsible for causing this issue has been completely removed, maybe you could open a seperate issue, and include some code & stack trace
