### ISSUE TITLE
sendLocalImage() Error

### ISSUE THREAD

**Issue by HiteshPatel0101** [carpedm20/fbchat#242] opened 2018-01-08 20:09 UTC
Hi,

getting error while uploading local png image.
PS : I am using Python 2.7.x
```
Exception in parsing of {u'queue': <removed>L, u'ofd_ts': <removed>L,
u'iseq': 138295, u'type': u'delta', u'delta': {u'body': u'screenshot-a', u'irisS
eqId': u'138295', u'class': u'NewMessage', u'attachments': [], u'messageMetadata
': {u'tags': [u'source:titan:m_basic'], u'actorFbId': u'<removed>', u'mess
ageId': u'mid.$<removed>', u'offlineThreadingId': u'<removed>
<removed>', u'timestamp': u'<removed>', u'threadKey': {u'otherUserFbId': u
'<removed>'}}}}
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\fbchat\client.py", line 1520, in _parseMes
sage
    thread_id=thread_id, thread_type=thread_type, ts=ts, metadata=metadata, msg=
m)
  File "C:\Other\tp\Research\Python\FB_Terminal\FBTerminal.py", line 31, in onMe
ssage
    self.sendLocalImage(image_path, Message(text='screenshot'), thread_id=thread
_id, thread_type=thread_type)
  File "C:\Python27\lib\site-packages\fbchat\client.py", line 1038, in sendLocal
Image
    image_id = self._uploadImage(image_path, open(image_path, 'rb'), mimetype)
  File "C:\Python27\lib\site-packages\fbchat\client.py", line 981, in _uploadIma
ge
    return j['payload']['metadata'][0]['image_id']
IndexError: list index out of range
```

**Comment by madsmtm** [comment] 2018-01-08 21:00
Related to #231, but again, I can't reproduce this, perhaps you can provide me the image that it's failing on? What does your code look like?

**Comment by HiteshPatel0101** [comment] 2018-01-09 07:06
Login 
Onmessage API
Once received 'screenshot' it will capture screenshot and send it to specific authenticated user. 

Code Snippet:
--------------------------------------------------------------------------------------------
pic = pyautogui.screenshot()
pic.save('Screenshot.png')
image_path=os.getcwd()+'\\Screenshot.png'
print image_path
if author_id != self.uid:
      self.sendLocalImage(image_path, message=Message(text='screenshot'), thread_id=thread_id, thread_type=thread_type)   

___________________________________________________________________________________

**Comment by madsmtm** [comment] 2018-01-09 15:10
Maybe the image is not properly loaded, since the path is invalid? Perhaps it should be `image_path=os.getcwd()+'\\Screenshot.png'` instead of `image_path=os.getcwd()+'\Screenshot.png'`. Or maybe `image_path=os.getcwd()+'/Screenshot.png'`?

**Comment by HiteshPatel0101** [comment] 2018-01-12 11:30
i have tried both but still getting same error. ;-(

**Comment by madsmtm** [comment] 2018-01-12 13:00
Again, can you provide me the image? And also, you're sure that you are actually running the script from you current working directory?

**Comment by norbi97** [comment] 2018-02-09 19:24
If i use IDLE to run the script, i get the same error. When i ran it from the command line, it worked though.
As a workaround, i just made a start.bat file which simply has "python script.py" in it.
That way it works. Maybe permission issues?
Hope it helps somehow.

**Comment by LordJB** [comment] 2018-02-09 23:11
So I'am having the same problem. 

My project in which I use fbchat is here (https://github.com/LordJB/audadopi/blob/master/audadopi_0_0_1.ipynb)

My picture is:
![180209](https://user-images.githubusercontent.com/23332662/36054442-c073be92-0df6-11e8-989f-f3be0f0400a6.jpg)

**Comment by madsmtm** [comment] 2018-02-18 19:48
Hmm, still can't reproduce, maybe an issue that only exists on Windows. I've found that in `_uploadImage()`, Facebook doesn't return a `image_id` or a `gif_id`, it returns a `file_id`, when the `mimetype` is invalid. So perhaps an incorrect mimetype is returned by `mimetypes.guess_type()`? Maybe someone who's having this problem could try providing the output of this (with their `image_path` provied):
```py
from mimetypes import guess_type
print(guess_type(image_path))
```

**Comment by rexx0520** [comment] 2018-03-03 07:30
Similar Error when uploading webp as photo
```
return j['payload']['metadata'][0]['image_id']
KeyError: 'image_id'
```

**Comment by alecglen** [comment] 2018-07-23 17:51
Also getting this issue. I investigated the mimetype, but it seems to be working fine (e.g. `('image/jpeg', None)` for a .jpg; `('image/gif', None)` for a .gif).

However, I do see the same issue with Facebook not returning an `image_id`.  Specifically, the response I get is:
`{'__ar': 1, 'payload': {'uploadID': None, 'metadata': []}, 'bootloadable': {}, 'ixData': {}, 'gkxData': {}, 'lid': '6581463857660260794'}`. 

I tried posting with the `lid` value instead, but only got the below error back from Facebook:
`Error #1545012 when sending request: There was a temporary error, please try again.`

Any suggestions?

**Comment by madsmtm** [comment] 2018-08-12 18:04
Hmm, been a while since I investigated this, maybe you can try uploading the problematic image on facebook.com, and try analysing the request they're sending, compared to the one we are sending?

**Comment by madsmtm** [comment] 2018-08-29 22:52
I've now had a similar issue myself, and got to see it happen in the browser, so I'll conclude this as Facebook's fault ;)

**Comment by madsmtm** [comment] 2020-01-09 11:16
Closing, see above comment. Also, I'm fairly certain `fbchat` has changed a lot since this issue was created, so not even sure if it's relevant any more...

**Closed by madsmtm** 2020-01-09 11:16 UTC
Labels: bug
